
executable              = $(directory)/DistributionPlots.sh
arguments               = /afs/cern.ch/user/g/geliu/LepUni_incl/CMSSW_10_6_26/src/HTauTauHMuMu/AnalysisStep/test/Plotter/$(directory) $(ClusterId)$(ProcId)
output                  = log/$(ClusterId).$(ProcId).out
error                   = log/$(ClusterId).$(ProcId).err
log                     = log/$(ClusterId).log
Initialdir              = $(directory)

+JobFlavour             = "workday"

#https://www-auth.cs.wisc.edu/lists/htcondor-users/2010-September/msg00009.shtml
periodic_remove         = false
